name: .NET Framework Build

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setput MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGetPackages
        run: nuget MonitorServer.sln restore

      - name: Build App
        run: msbuild MonitorServer.sln /p:Configuration=Release
