name: .NET Framework

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --verbosity normal
